name: Build and Deploy

on:
  push:
    branches:
      # - 'env/**'
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.3.0
          cache: 'npm'

      - run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to Amazon S3
        uses: Reggionick/s3-deploy@v3.1.1
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          private: true
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}

          dist-id: ${{ secrets.CF_DISTRIBUTION }}
          invalidation: /*
