name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

  push:
    branches:
      - 'env/**'
      - main


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # TODO: investigate how to assume role to follow best practices
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
          cache: 'npm'

      - run: npm ci

      - name: Build application
        env: 
          CI: false
        run: npm run build

      - name: Deploy to Amazon S3
        uses: Reggionick/s3-deploy@v3.1.1
        with:
          folder: build

          bucket: ${{ secrets.S3_BUCKET_NAME }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          private: true

          dist-id: ${{ secrets.DISTRIBUTION_ID }}
          invalidation: /*
